### ISSUE TITLE
Got "OSError: [Errno 9] Bad file descriptor" when running function"magic"

### ISSUE THREAD

**Issue by goubegou** [KrishnaswamyLab/MAGIC#125]
Hi MAGIC developer,
     I've been using MAGIC for several weeks and it worked well, but these days when i ran function "magic"
`data <- magic(data, genes='all_genes', 
                     t=4)`

 i got following error:

> Calculating MAGIC...
Calculating graph and diffusion operator...
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\goubegou\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\logging.py", line 29, in write_r_safe
    os.write(1, bytes(msg, 'utf8'))
OSError: [Errno 9] Bad file descriptor
Call stack:
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\magic_impute-1.2.1-py3.7.egg\magic\magic.py", line 530, in fit_transform
    self.fit(X)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\magic_impute-1.2.1-py3.7.egg\magic\magic.py", line 373, in fit
    random_state=self.random_state)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\api.py", line 232, in Graph
    return Graph(**params)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\graphs.py", line 80, in __init__
    super().__init__(data, n_pca=n_pca, **kwargs)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\base.py", line 601, in __init__
    super().__init__(data, **kwargs)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\base.py", line 130, in __init__
    self.data_nu = self._reduce_data()
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\base.py", line 155, in _reduce_data
    log_start("PCA")
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\logging.py", line 109, in log_start
    get_task_logger().start_task(name)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\logging.py", line 50, in start_task
    self.log("Calculating {}...".format(name))
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\logging.py", line 46, in log
    self.logger.info(msg)
Message: 'Calculating PCA...'
Arguments: ()
Error in py_call_impl(callable, dots$args, dots$keywords) : MemoryError: 

Detailed traceback: 
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\magic_impute-1.2.1-py3.7.egg\magic\magic.py", line 530, in fit_transform
    self.fit(X)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\magic_impute-1.2.1-py3.7.egg\magic\magic.py", line 373, in fit
    random_state=self.random_state)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\api.py", line 232, in Graph
    return Graph(**params)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\graphs.py", line 80, in __init__
    super().__init__(data, n_pca=n_pca, **kwargs)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9-py3.7.egg\graphtools\base.py", line 601, in __init__
    super().__init__(data, **kwargs)
  File "C:\Users\goubegou\AppData\Roaming\Python\Python37\site-packages\graphtools-0.1.9

I'm not a python user, and i think i haven't change any setting about python.The original installation and settings of python and depending python packages were done according to your introduciton on github. I wonder why this bug happen. Wish to learn from you about how to fix this bug. Thanks a lot!

**Comment by scottgigante** [comment]
Hi @goubegou,

**Comment by scottgigante** [comment]
Hi @goubegou,

There are two errors going on here. 

The first is a logging error - it appears that the stout file stream has been closed. What operating system are you running on and does this error occur when you run, for example, the code from the MAGIC tutorial notebook?

The second (and more important) error is a memory error. How large is your matrix and how much memory does your computer have spare? You might consider rethinking the choice of genes="all_genes" if you have a large matrix.

**Comment by goubegou** [comment]
Thanks for your guide @scottgigante . I run MAGIC on Windows . I re-run MAGIC on smaller data and found logging error still present, but MAGIC has completed the calculation. I guess i can ignore the logging error and use the result? If i run MAGIC on computer with higher performance, will i be able to overcome the memory error, or its a limitation of MAGIC itself? Thank you.

**Comment by scottgigante** [comment]
Hi @goubegou,

Glad to hear it. The memory issue is indeed an issue of machine performance. As I mentioned above, if you use `genes="GENE"` (replacing GENE with a gene or list of genes that interest you) then you will be able to use MAGIC on your computer - the issue here is that with a dense matrix (i.e. most values are non-zero) your computer simply doesn't have enough memory to store the full gene expression matrix. Another alternative is to subsample the cells, or otherwise of course you can use a more powerful computer.

The logging issue is odd but inconsequential. If you want to investigate it further, I would ask you to run the following lines in python: 
```
from builtins import bytes
import os
import sys
sys.stdout.write("test sys") 
os.write(1, bytes("test os", "utf8")) 
```
Let me know if that gives you an error.

**Comment by scottgigante** [comment]
I'm closing this due to inactivity. Feel free to reopen it if you'd like to investigate this logging issue further.
