### ISSUE TITLE
scprep==0.10.0

### ISSUE THREAD

**Issue by Dangertrip** [KrishnaswamyLab/MAGIC#149]
Have to install scprep==0.10.0 when using MAGIC in python3.6
Higher version of scperp doesn't work for MAGIC.
Plz notice and change the requirement~

**Comment by scottgigante** [comment]
Hi @Dangertrip , can you please explain what doesn't work about higher versions of scprep with MAGIC?

**Comment by Dangertrip** [comment]
I use pip to install scprep in python3.6
But when I run "import magic", error was reported.
I reinstalled scprep==0.10.0 and no error appears again.
I'm using Mac here.
Here's my error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yyin/.local/lib/python3.6/site-packages/magic/__init__.py", line 3, in <module>
    from .magic import MAGIC
  File "/Users/yyin/.local/lib/python3.6/site-packages/magic/magic.py", line 22, in <module>
    import scprep
  File "/Users/yyin/.local/lib/python3.6/site-packages/scprep/__init__.py", line 5, in <module>
    import scprep.io
  File "/Users/yyin/.local/lib/python3.6/site-packages/scprep/io/__init__.py", line 6, in <module>
    from .fcs import load_fcs
  File "/Users/yyin/.local/lib/python3.6/site-packages/scprep/io/fcs.py", line 225, in <module>
    @utils._with_pkg("fcsparser")
  File "<decorator-gen-1>", line 2, in _with_pkg
  File "/Users/yyin/anaconda3/lib/python3.6/site-packages/decorator.py", line 228, in decorate
    evaldict, __wrapped__=func)
  File "/Users/yyin/anaconda3/lib/python3.6/site-packages/decorator.py", line 208, in create
    name, rest = obj.strip().split('(', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by scottgigante** [comment]
This is an issue with `scprep`, moving the conversation over there.

**Comment by scottgigante** [comment]
@Dangertrip just to be clear, I have reopened this issue at https://github.com/KrishnaswamyLab/scprep#33

**Comment by scottgigante** [comment]
@Dangertrip should be all fixed now. `pip install --upgrade magic-impute` will have you all set.

**Comment by Dangertrip** [comment]
Sorry about the delay. I just came back in town today. Thank you for solving this problem!
