### ISSUE TITLE
Error when trying to run magic

### ISSUE THREAD

**Issue by kbrulois** [KrishnaswamyLab/MAGIC#44]
I'm having trouble getting MAGIC.py to run. Tried the gui and command line. I'm using macOS 10.12.5 Python stops responding and it gives this error message:

(python3) SLE-BTR-C02TN2K4HF1R:magic kevin$ MAGIC.py -d /Users/kevin/Desktop/test.csv -o /Users/kevin/Desktop/ csv
^CTraceback (most recent call last):
  File "/usr/local/bin/MAGIC.py", line 112, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/MAGIC.py", line 95, in main
    scdata.filter_scseq_data(filter_cell_min=args.mols_per_cell_min, filter_cell_max=args.mols_per_cell_max)
  File "/usr/local/lib/python3.6/site-packages/magic/mg.py", line 476, in filter_scseq_data
    self.data = self.data.ix[self.data.index[to_keep], :].astype(np.float32)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 118, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 856, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1059, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1118, in _getitem_iterable
    keyarr)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2916, in _reindex_non_unique
    indexer, missing = self.get_indexer_non_unique(target)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2708, in get_indexer_non_unique
    indexer, missing = self._engine.get_indexer_non_unique(tgt_values)
  File "pandas/_libs/index.pyx", line 356, in pandas._libs.index.IndexEngine.get_indexer_non_unique (pandas/_libs/index.c:8161)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1136, in resize
    a = concatenate((a,)*n_copies)
KeyboardInterrupt

**Comment by pkathail** [comment]
Could you post the full stack trace of the error or is it too long? With the keyboard interrupt it's difficult to determine the reason for the error

**Comment by danieldager** [comment]
Hi kbrulois,

There's a good chance that these problems were resolved with the release of MAGIC v1.0. Uninstall your current version of MAGIC and reinstall per the directions of the new README. I'm closing this for now; please feel free to open a new issue if you still have problems!
